# Generated by Django 5.0.7 on 2024-10-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_employee_employee_type_alter_employee_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='dsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('pan', models.CharField(blank=True, max_length=12, null=True)),
                ('aadhar', models.CharField(max_length=12)),
                ('profession', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('acc_number', models.CharField(max_length=30)),
                ('acc_holder_name', models.CharField(max_length=30)),
                ('bank_name', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=40)),
                ('branch_name', models.CharField(max_length=20)),
                ('agreeCheck', models.BooleanField(default=False)),
                ('approval_status', models.CharField(default='pending', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('PersonalLoan', 'Personal Loan'), ('HomeLoan', 'Home Loan'), ('CarLoan', 'Car Loan'), ('EducationLoan', 'Education Loan'), ('LapLoan', 'LAP Loan'), ('OtherLoan', 'Other Loan'), ('BusinessLoan', 'Business Loan'), ('GoldLoan', 'Gold Loan'), ('CreditCard', 'Credit Card '), ('OtherEmployee', 'OtherEmployee')], max_length=20),
        ),
    ]
