# Generated by Django 5.0.7 on 2024-10-16 11:22

import manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_dsa_alter_employee_employee_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('pan', models.CharField(blank=True, max_length=12, null=True)),
                ('aadhar', models.CharField(max_length=12)),
                ('profession', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('agreeCheck', models.BooleanField(default=False)),
                ('dsaPhoto', models.ImageField(upload_to='dsa/', validators=[manager.models.validate_image_file])),
                ('aadharFront', models.ImageField(upload_to='dsa/', validators=[manager.models.validate_image_file])),
                ('aadharBack', models.ImageField(upload_to='dsa/', validators=[manager.models.validate_image_file])),
                ('panCard', models.ImageField(upload_to='dsa/', validators=[manager.models.validate_image_file])),
                ('bankDocument', models.ImageField(upload_to='dsa/', validators=[manager.models.validate_image_file])),
                ('approval_status', models.CharField(default='pending', max_length=20)),
            ],
        ),
    ]
