# Generated by Django 5.0.7 on 2024-10-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_franchise_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchise',
            name='approval_status',
        ),
        migrations.AddField(
            model_name='franchise',
            name='aproval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
