# Generated by Django 5.0.7 on 2024-10-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_remove_franchise_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsa',
            name='dsa_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
