# Generated by Django 5.0.7 on 2024-10-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_dsa_dsa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsa',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='dsa',
            name='dsa_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
