# Generated by Django 5.0.7 on 2024-10-25 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_alter_dsa_approval_status_alter_dsa_dsa_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='dsaowner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_id', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=128)),
                ('franchiseid', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='franchiseower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_id', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=128)),
                ('employee_type', models.CharField(choices=[('Sales', 'Sales'), ('Customer', 'Customer'), ('Account', 'Account')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='dsa',
            name='franchiserefcode',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerid', models.CharField(max_length=100)),
                ('franchiseCode', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('pan', models.CharField(blank=True, max_length=12, null=True)),
                ('aadhar', models.CharField(max_length=12, null=True)),
                ('qualification', models.CharField(max_length=30, null=True)),
                ('approval_status', models.CharField(default='pending', max_length=20, null=True)),
                ('Employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
