# Generated by Django 5.0.7 on 2024-10-25 09:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_dsaowner_franchiseower_dsa_franchiserefcode_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='franchisecode',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
