# Generated by Django 5.0.7 on 2024-10-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_custmer_dsausers_franchisesales_franchiseusers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsausers',
            name='dsa_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
