# Generated by Django 5.0.7 on 2024-10-25 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_alter_dsausers_dsa_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsa',
            name='dsa_id',
        ),
        migrations.RemoveField(
            model_name='dsa',
            name='name',
        ),
    ]
