# Generated by Django 5.0.7 on 2024-10-25 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_remove_dsa_dsa_id_remove_dsa_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsa',
            name='dsa_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dsa',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
