# Generated by Django 5.0.7 on 2024-10-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_dsa_dsa_id_dsa_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsa',
            name='dsa_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dsa',
            name='dsa_registerid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
