# Generated by Django 5.0.7 on 2024-10-29 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_alter_dsa_dsa_name_alter_dsa_dsa_registerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsa',
            name='dsa_id',
        ),
        migrations.RemoveField(
            model_name='dsa',
            name='name',
        ),
    ]
