# Generated by Django 5.0.7 on 2024-11-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_employee_phone_number_alter_employee_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('PersonalLoan', 'Personal Loan'), ('HomeLoan', 'Home Loan'), ('CarLoan', 'Car Loan'), ('EducationLoan', 'Education Loan'), ('LapLoan', 'LAP Loan'), ('OtherLoan', 'Other Loan'), ('BusinessLoan', 'Business Loan'), ('GoldLoan', 'Gold Loan'), ('CreditCard', 'Credit Card '), ('OtherEmployee', 'OtherEmployee'), ('sales', 'sales')], max_length=20),
        ),
    ]
